# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# The main all target
all: 
	mkdir -p build && g++ ./src/main.cpp -o build/Trie_Search && cd build && ./Trie_Search

cmp: 
	g++ ./src/main.cpp -o build/Trie_Search

run: 
	cd build && ./Trie_Search

.PHONY : all
